### ISSUE TITLE
valuation of embezzlers

### ISSUE THREAD

**Issue by docrostov** [Loathing-Associates-Scripting-Society/garbage-collector#1145]
okay i have a thought here. we store embezzlers as 3x VOA in a lot of different places. what if we start changing that to valueOfEmbezzler upwards in lib.ts, make that equal to 3x VOA for now, swap it out in the various locations it's done, and someday have better evaluation procedures? this way if we ever do a better job evaluating it we only have to do it in one spot.

_Originally posted by @docrostov in https://github.com/Loathing-Associates-Scripting-Society/garbage-collector/pull/1143#discussion_r989383029_

i think this is a good idea and something we should try to do

**Comment by horrible-little-slime** [comment]
Truly better valuation of embezzler's is garbo's biggest white whale, but this will make life easier when we harpoon her.
