### ISSUE TITLE
renaming cost in vykea function

### ISSUE THREAD

**Issue by docrostov** [Loathing-Associates-Scripting-Society/garbage-collector#1148]
okay i realize that this Works :tm: but i would recommend renaming "cost" here. the cost that is being used is the dowelCost, whereas the vykeaCost is the thing actually being calculated. by just naming it cost it reads like there's double counting going on until you reread the whole thing.

_Originally posted by @docrostov in https://github.com/Loathing-Associates-Scripting-Society/garbage-collector/pull/1143#discussion_r989369143_

**Comment by horrible-little-slime** [comment]
This one I actually did wrap up into my PR
