### ISSUE TITLE
Multiple Lucky! Embezzlers being chained back to back

### ISSUE THREAD

**Issue by Alium58** [Loathing-Associates-Scripting-Society/garbage-collector#1172]
Attached log has sequence of shore -> lucky embezzler -> lucky embezzler -> lucky embezzler -> warren.

Based on discussion in discord, only one lucky embezzler is needed. I don't understand kol mechanics well enough myself to confirm/deny this. 
[GarboLuckyAdvs.txt](https://github.com/Loathing-Associates-Scripting-Society/garbage-collector/files/9844754/GarboLuckyAdvs.txt)

**Comment by horrible-little-slime** [comment]
Haven't heard of this happening in quite some time. Additionally, this is a symptom rather than a disease itself; closing until it re-emerges from the depths.
