### ISSUE TITLE
Doesn't work well for lower skill lower IOTM chars

### ISSUE THREAD

**Issue by apenny1313** [Loathing-Associates-Scripting-Society/garbage-collector#1275]

**Comment by s-k-z** [comment]
Can you provide any details?

**Comment by apenny1313** [comment]
So - I notice my main (apenny) and a couple of my higher skill/higher IOTM chars make meat using garbo but say "silver nickel" or "Mafia Pumpkin" do not.  I have had several clannies with similar problems so seems like it isn't just me.  No idea why.  You can kmail me on apenny if you have a specific question.

**Comment by Fawoosh** [comment]
https://github.com/Loathing-Associates-Scripting-Society/garbage-collector#is-garbo-for-me
