### ISSUE TITLE
[bug] need to expand spleen consideration 

### ISSUE THREAD

**Issue by docrostov** [Loathing-Associates-Scripting-Society/garbage-collector#1297]
https://github.com/Loathing-Associates-Scripting-Society/garbage-collector/blob/00188b1392466335ea159fd01b34c1fc05195cd9/src/diet.ts#L363

user reported the script was not considering agua. i figured there wouldn't be a world where we'd want to do agua but i was wrong. current prices are agua de vida = 5482 for 4 spleen @ 1.88 advs per spleen, versus transdermal smoke patch at 1 spleen @ 2.5 adv per spleen. i did a quick table and the user is correct. the loss is relatively low at the 5500-6000 range most of us are at but is more noticeable at lower levels where min VOA users are probably missing out on roughly 20k meat per day; not much but not nothing. easy PR to just add in other spleeners things but i am going to bed lol

![image](https://user-images.githubusercontent.com/8014761/221105528-306d6b28-61ce-4920-bccb-9d42719ef4a4.png)

**Comment by horrible-little-slime** [comment]
I would describe this as a feature request rather than a bug. but yeah this should be pretty doable.

Could you round up a list of all equivalent spleen items?

**Comment by docrostov** [comment]
resolved in #1303. 

(i will take issue with this as a feature request vs a bug. i think this is a straightforward enough add -- and the PR was easy enough -- that it is worth saying "our diet was not considering any of like 30 readily available spleen items" was kind of a bug because it meant for non-extro/jelly folks garbo was leaving a decent gob of spleen-y value on the table. :<)
