### ISSUE TITLE
Garbo has round mismatch when encountering knobgoblin embezzlers 

### ISSUE THREAD

**Issue by Fabio11234** [Loathing-Associates-Scripting-Society/garbage-collector#13]
<img width="818" alt="Screen Shot 2021-05-17 at 12 29 22 PM" src="https://user-images.githubusercontent.com/13920570/118524121-d1f5c400-b70b-11eb-94ea-75f91baffeb8.png">

**Comment by Fabio11234** [comment]
every digitized embezzler shows up with this, and the dialog "Macro Aborted ("abort")" in the relay

**Comment by Malibu-Stacey** [comment]
looks like a duplicate of #9
