### ISSUE TITLE
Not Rebinding Lasagmbie after Free fights

### ISSUE THREAD

**Issue by Prusias-kol** [Loathing-Associates-Scripting-Society/garbage-collector#1370]
Basically title. I ensure I equip lasagmbie before running garbo and garbo unbinds it and never rebinds it.

Here's a log from right before I call garbo. The bind lasagmbie bit all the way to glenn's dice is my personal wrapper and 
[Prusias_20230430.txt](https://github.com/Loathing-Associates-Scripting-Society/garbage-collector/files/11362578/Prusias_20230430.txt)
Here's my lasagmbie after running garbo (I had to cast bind lasagmbie cuz i had no pasta thrall active)
<img width="273" alt="Screen Shot 2023-04-30 at 4 10 05 PM" src="https://user-images.githubusercontent.com/121605604/235380274-db8ef110-ce99-4df3-bf85-a0be130a06d5.png">

**Comment by docrostov** [comment]
resolved in #1371 -- thank you for the report, please let us know if the issue recurs! 👍
