### ISSUE TITLE
Combat exception when can kill monster with weapon

### ISSUE THREAD

**Issue by apenny13** [Loathing-Associates-Scripting-Society/garbage-collector#1451]
avaScript exception: Combat exception! Last macro error: Macro Aborted ("abort"). Exception Combat exception! Last macro error: Macro Aborted ("abort"). Exception KoLmafia error: You're on your own, partner. (Macro Aborted ("abort"))..

Garbo craps out on fights it could easily win with attack wit weapon.  I was surprised to get this error on my level 28 seal clubber fighting a rather easy fluffy bunny.  My level 15 sauceror was also quite able to kill the embezzler with attack with weapon.

**Comment by Rinn** [comment]
garbo doesn't want to kill the monster, its aborting because it's trying to use a skill or item you don't have access to because mafia tracking is off. This is most likely due to either running turns outside of mafia, or because of the rampant page errors that kol is returning right now.
