### ISSUE TITLE
[resource] utilize chateau

### ISSUE THREAD

**Issue by docrostov** [Loathing-Associates-Scripting-Society/garbage-collector#195]
two major chateau things:

- utilize the chateau copy to fight another embezzler
- grab your daily drop of random potions from the desk drawer

you could also use the free rests for stats

**Comment by horrible-little-slime** [comment]
First half is #111

**Comment by horrible-little-slime** [comment]
non-ascending nightcap should get the skylight if you currently have ceiling fan--perhaps introduce a valueOfFite property to determine if it beats the antlers?
