### ISSUE TITLE
[resource] free pillkeeper usage

### ISSUE THREAD

**Issue by docrostov** [Loathing-Associates-Scripting-Society/garbage-collector#197]
there is some code that utilizes free pillkeeper to double frost flower -- this is clever and good, but it does not work if frost flowers are too expensive. i would refactor this slightly such that it checks if you are in CS aftercore, and if you are not, it uses the free pillkeeper to encounter an embezzler in the knob treasury. if you are in CS aftercore, assuming price of eyedrops > MPA, i think you can still justify using your free pillkeeper at the end of the day to grab a cyclops eyedrops.

**Comment by horrible-little-slime** [comment]
#111 for not CS; we don't currently use it for CS
