### ISSUE TITLE
[resource] seek out a bird skill usage

### ISSUE THREAD

**Issue by docrostov** [Loathing-Associates-Scripting-Society/garbage-collector#200]
minimum viable product for this should just be to use it 5 times at the start of the day in case it's a +meat skill. it probably would be good to do a check too, tho, because you may have bird buff turns remaining from yesterday, and if those are meat% it should probably just ignore bird buff for that day (or cast it once the remaining bird buff turns are done)

**Comment by Rinn** [comment]
This is done, forgot to link the issue to my PR before it was merged.
