### ISSUE TITLE
[resource] asdon marten freekill/yr

### ISSUE THREAD

**Issue by docrostov** [Loathing-Associates-Scripting-Society/garbage-collector#203]
for 100 fuel, the asdon marten workshed item allows you to get a freekill no-ELY yellow ray. this should be used in some way. i think the minimum viable product for it would be to use it as an extra freekill for a sandworm. maximally, it would be used in concert with your duplicate and a map on some useful target for a dupe

**Comment by horrible-little-slime** [comment]
Resolved by #102
