### ISSUE TITLE
[resource] use free runs profitably

### ISSUE THREAD

**Issue by docrostov** [Loathing-Associates-Scripting-Society/garbage-collector#204]
currently, i don't think that garbo utilizes free runs for bander or boots. i think it would be a relatively easy thing to -place-, but it is not super straightforward what the runs should be used for. 

- first, it should be used to get latte ingredients (i believe this is already coded)
- the best usage is likely gingerbread city candy/cigarettes, for guaranteed profit
- if the user does -not- have gingerbread city, in non-CS aftercore, could be used for UR hunting (thinking especially of knob menagerie or icy peak, but peak requires com% management)
- if the user is in CS aftercore, could be used to UR hunt but -definitely- requires com% management

happy for ideas on this but i think free run usage pairs well with the current famweight push right before you profcopy embezzlers. i think it's a worthy usage but might be annoying to do, as the zones you want to free run in may not be open...

**Comment by docrostov** [comment]
actually, instead of making a new issue i will add this here -- one other connected resource to free run handling is mayfly runs, which can only be used in the knob menagerie anyway. searching for an ultra-rare with those runs is silly but has a potential to turn a 4-5 million meat day into a 300 million meat day, which is (even at absurdly low percentages) probably worth it if it costs you nothing to do.

**Comment by horrible-little-slime** [comment]
Scotch is correct that it is used for latte, and we have architecture in place that would make it easier to implement other run resources now

**Comment by horrible-little-slime** [comment]
Related to #232

**Comment by horrible-little-slime** [comment]
Unearthed because this is an eternal flame
