### ISSUE TITLE
[resource] use etched hourglass

### ISSUE THREAD

**Issue by docrostov** [Loathing-Associates-Scripting-Society/garbage-collector#206]
this may already be fixed, but etched hourglass does not seem to always use? very often the first time it gets used is when i run breakfast at the end of the day. probably worth looking into.

**Comment by horrible-little-slime** [comment]
It gets used as breakfast, which may make this unnecessary

**Comment by docrostov** [comment]
i would say that as a turn-generating device it probably should be used right around when garbo uses stuff like essential tofu, because there is a chance (albeit a low one) that the user breakfasts at the end of the day and loses the turns. but i agree, if we consider breakfast stuff out of scope, this is out of scope lol

**Comment by horrible-little-slime** [comment]
Resolved by #134
