### ISSUE TITLE
[resource] acquire volcoino

### ISSUE THREAD

**Issue by docrostov** [Loathing-Associates-Scripting-Society/garbage-collector#208]
if the user has access to That 70s Volcano (lol) and hasn't already acquired it, garbo should grab the daily volcoino. for extra credit, might be worth considering if there are a few sidequests worth doing for another volcoino; those things are -expensive- and there are certain use cases where turns spent on the quest volcoino have higher MPA than your marginal end-of-day barf turns.

**Comment by horrible-little-slime** [comment]
#116
