### ISSUE TITLE
We need a readme

### ISSUE THREAD

**Issue by Phillammon** [Loathing-Associates-Scripting-Society/garbage-collector#21]
the important bit is `svn checkout https://github.com/Loathing-Associates-Scripting-Society/garbage-collector/branches/main/KoLmafia/` but more might be useful too

**Comment by docrostov** [comment]
including a bit re: clan stash & an introduction to what this script does and does not do would be good. no nightcap is an important callout tbh, many users will likely expect it will just do their whole day for them and it is pointedly not written to do that, it is just trying to burn barf turns. readme.md should also ideally be encased in a garbo help command that can be called from CLI mb.

**Comment by docrostov** [comment]
making a note for myself that the one you noted here didn't work for someone for whatever reason (maybe they already had a scripts folder and it caused some dumb issue) but this one did:

svn checkout https://github.com/Loathing-Associates-Scripting-Society/garbage-collector/KoLmafia/scripts/garbage-collector/

**Comment by docrostov** [comment]
nvm what the hell
