### ISSUE TITLE
[resource] guzzlr

### ISSUE THREAD

**Issue by docrostov** [Loathing-Associates-Scripting-Society/garbage-collector#213]
this can be as complicated or as simple as you want it

at a minimal level of complication, just get the platinum guzzlr kit so the user can sell them in the mall

at a maximal level of complication, get other guzzlr quests and place wanderers in those zones to complete them for meat and guzzlr advancement. i -think- this logic is already installed but figured we'd make an issue to close it if it actually is done.

**Comment by horrible-little-slime** [comment]
Largely resolved by #83, although it is an eternal flame
