### ISSUE TITLE
[resource] free crafts

### ISSUE THREAD

**Issue by docrostov** [Loathing-Associates-Scripting-Society/garbage-collector#217]
for high end shiny users, there are a ton of daily free crafts. i think it is likely there is -some- useful usage for these, but i am not entirely sure what. if they are a sauceror, sauce potions are probably good. beyond that, not sure. (also, users with thor's pliers have an additional 10 free meatsmithings per day; no idea whatsoever what to use those on, but there might be something. worth a good think!)

**Comment by horrible-little-slime** [comment]
we now do key limes hell yeah
