### ISSUE TITLE
[BUG] Fails if unable to access Spookraven Bedroom

### ISSUE THREAD

**Issue by Doucy13** [Loathing-Associates-Scripting-Society/garbage-collector#2170]
**Describe the bug**
When running with an account that doesn't have access to Spookyraven Bedroom, it starts looping the following:

Executing Wanderers/Lights Out

Visit to Manor2: The Haunted Bedroom in progress...
You can't get to that area.

**To Reproduce**

ran GARBO from Mafia CLI

**Expected behavior**
Confirms access to this area before attempting to use this route?

**Session Log**
[mylltn2_20241120.txt](https://github.com/user-attachments/files/17832617/mylltn2_20241120.txt)
Line 7874 onward.

**Additional context**
To be frank, I suspect this is a super edge case and am mainly logging it out of bemusement.
This account hadn't read the Telegram from Lady Spookyraven or progressed the unlocks due to being a very (multi-year) long ascension and a mostly idle account.
Entirely expecting the answer to be "ascend the account / unlock spookyraven" but I'll leave them be in case anyone is curious and wants to look in to it! :)

**Comment by Doucy13** [comment]
Sorry, I realise the reproduction is basically useless but unless time travel becomes an option I don't think it can be done!

**Comment by horrible-little-slime** [comment]
Garbo does currently check access using mafia's `can_adventure`, which is to say that mafia is what's incorrectly tracking zone access rather than garbo. That being said the best solution is just to ascend.
