### ISSUE TITLE
nightcap functionality in garbo

### ISSUE THREAD

**Issue by docrostov** [Loathing-Associates-Scripting-Society/garbage-collector#222]
okay so i am going to make this an issue. i do not think this is a critical path feature but i really think there should be nightcap functionality in garbo. when asking about this before i have seen it referred to as out of scope but i think that is mostly due to misunderstandings, as bean stated here that the lack of nightcap was more due to his specific script sequencing rather than an explicit design choice:

![image](https://user-images.githubusercontent.com/8014761/125130052-52aebc00-e0ce-11eb-9067-6a47be1d359e.png)

the design of a low-effort nightcap would be rather simple: 

- equip stooper (if you have it), buy/drink a splendid martini, with ode
- buy/drink a mugged jar of fermented pickle juice
- buy/chew a voodoo snuff and an antimatter wad
- equip lefty 
- maximize for rollover adventures
- buy 69 raffle tickets (this is a joke) (nice)

obviously there is more that can be done to make this a full feature implementation; autoscend has some interesting nightcap stuff we might be able to use too. but i think the above convo means that nightcaps are not functionally out of scope and can be considered a possible future improvement to garbo, even if it is not a critical path feature or fix.

**Comment by horrible-little-slime** [comment]
A few deviations from the low-effort nightcap that may be worth it:
 - consider sacramento+pinky ring if you have one, and look at eye & a twist as another option. Obivously check for pilsners as well. This is for stoopering
 - consider nightcapping with a vintage smart drink (+20 lbs for all of turn 0 the next day is good when not ascending)
 - run overdrunk adventures afterwards if the ascend tag is true
 - get a fused fuse with clara's bell if relevant after stoopering, but before regular drinking
 - whitelist to a nighttime clan(?)
 - melf dupe capacity (only worth it once we have a relay script, i think)

**Comment by phulin** [comment]
I want to add that you all should absolutely not consider my months-ago plans for garbo as binding in any way. This script is and was supposed to be owned by the community.

**Comment by docrostov** [comment]
moved content of this to #745
