### ISSUE TITLE
Moar Free Fights and Kramco/Voter Wanderer Catcher

### ISSUE THREAD

**Issue by Fawoosh** [Loathing-Associates-Scripting-Society/garbage-collector#23]
Add supports to fight Kramcos and Voter monsters as they are scheduled and free. The code would want to go in dailysetup and meatoutfit.

Add replica bat-oomerang to the list of free kills to use. (if it doesn't already)

Maybe track protoghosts and slam those when they crop up.

**Comment by Fawoosh** [comment]
Possibly Cargo Shorts monsters if that isn't a total nightmare to code.

**Comment by Phillammon** [comment]
Split into #29 #30 #31 #32
