### ISSUE TITLE
Track Maintenance?

### ISSUE THREAD

**Issue by rhcpbum3** [Loathing-Associates-Scripting-Society/garbage-collector#381]
Is there a way to track completing the quest of track maintenance if it is available? it seems like the convenience of the quest should make it profitable.

**Comment by horrible-little-slime** [comment]
@pstalcup I can't assign this to you yet on paper, but I can in spirit.

**Comment by Tokoeka** [comment]
Track Maintenance quest is completed by Garbo as of #1043
