### ISSUE TITLE
various unused iotm resources

### ISSUE THREAD

**Issue by docrostov** [Loathing-Associates-Scripting-Society/garbage-collector#40]
here are a variety of iotm resources that were not used after a day of garbofarmin', along with how they should be used. some are more complicated to handle than others.

- clan VIP pool table (+5 fam weight x3)
- zatara meatsmith buff (looks like logic is there, but needs to go to BAFH)
- cargo shorts (priority should be remaining bells > chess pieces > cursed pirate chocolate > ignore)
- time-spinner minutes (at minimum, get kardashian gin. at maximum, spend minutes on drunk pygmies in freefights)
- deck of every card draws (island, ancestral recall, 1952 mickey mantle)
- forest friars +fam xp buff, if not in community service (for extra prof xp)
- fight a chateau embezzler, if one exists
- use free pill, if frost flower is too expensive (just use for +1 embezzler, assuming non-CS aftercore)
- clip art (borrowed time or famjacks x3)
- seek out a bird skill (cast 5 times, could be meat/items)
- gaze at the stars at the getaway campsite (x4, +xp% then 3 possible meat buffs)
- asdon martin freekill/yellow ray
- free runs for gingerbread city candy & cigarettes while you are buffed up for professor copies
- numberology turns were not generated, i did that manually but should probably be part of diet handling
- did not use my etched hourglass though it did use lots of other weird stuff like tofu & borrowed time
- actually in general the borrowed time usage was weird to me, i do not understand why it uses it every day, seems like a waste if you aren't a looper

and here are some that i do not have but could in theory be used

- the +1 copy from rain doh + spooky putty
- volcoino (clearly worth it if you have daily volcano access)
- buddy bjorn handling to get some of those drops (or at minimum viable usage, golden monkey if you have it)
- mayfly runaways for UR fishing in the menagerie (this is super marginal and honestly dumb, but meh)
- tea tree? (this might already have handling idk, also maybe it's in breakfast)

**Comment by docrostov** [comment]
a few more
- arena concert from the war for +40% meat
- voting booth buffs; can be +item stuff, just patch into ezan's script here
- free platinum guzzlr drink kit
- space jellyfish extractions; can burn macros on stench or sleaze zones for 5 per day
- non-fam-weight beachcombs (for chance at a whale or rare)
- free crafts for, uh, idk, something (this is very marginal but there may be an easy to think of use)
- use reanimated reanimator on envyfish egg for +3 KGEs 
- use free BAFH fortune clan consults for chance at a skillbook

**Comment by horrible-little-slime** [comment]
Use mayo clinic (if already in workshed) during diet. Simplest possible answer is just getting a mayoflex every time you eat, but mayozapined horseradishes are, I believe, a staple of garbage diets.

**Comment by docrostov** [comment]
i have de-aggregated this mega-issue into individual issues that can be linked and closed. goodbye, mega-issue!
