### ISSUE TITLE
better distention/dog hair pill handling

### ISSUE THREAD

**Issue by docrostov** [Loathing-Associates-Scripting-Society/garbage-collector#54]
IMO, this should be done in a way that does not create an auto-block for people who don't have them unless they explicitly want it to create an auto-block for them. i'm personally fine with the default being to abort if you don't have a pill, but with the script currently unable to generate pills itself, i think there should be some sort of "garboSpacePillHandling" setting that can guide it to whether the default should be "notify but default ignore", "notify but default abort", "do not consider pills" depending on user preference. the ideal would be to get garbo in a place where it just gets your pills itself, but that requires resource usage, which becomes mildly confusing. still, i can port some of my pill code over and see if it's acceptable for implementation into garbo

**Comment by Phillammon** [comment]
Resolved by #103
