### ISSUE TITLE
If Tunnel of LOV has been visited prior to the script being run, it loops infinitely.

### ISSUE THREAD

**Issue by arroyo-flow** [Loathing-Associates-Scripting-Society/garbage-collector#602]

**Comment by horrible-little-slime** [comment]
Did you visit the tunnel outside of mafia / on a different computer?

**Comment by horrible-little-slime** [comment]
Closed; this issue was almost certainly caused by user error. Garbo relies on the assumption that what mafia tells it is true, and mafia relies on the assumption that you aren't cheating on it behind its back.
