### ISSUE TITLE
[resource] Garbo should swap worksheds, if configured to do so

### ISSUE THREAD

**Issue by pstalcup** [Loathing-Associates-Scripting-Society/garbage-collector#742]
Garbo could have a better idea of how to swap worksheds than any given user. For example, it could hypothetically swap to Asdon after it is done with getting pills from the CMC, or switch to CMC after it buffs up Driving Observantly for a certain number of turns

**Comment by horrible-little-slime** [comment]
note: for driving observantly, we conceivably want to switch after getting enough turns for the _next_ day as well.

For Mayo, pantsgiving throws a mild wrench in this.

It is very easy to find good "breakpoints" for each iotm, though. CMC you can swap out during postCombatActions if we've caught 'em all. Mayo can be swapped out either after the second pantsgiving fullness or after the primary diet. Asdon can be swapped out after the first big mood call. (note: kids no longer say "big mood", they just say "mood")

DNA support continues to have one tiny gadfly that ends up weirdly massive.

**Comment by pstalcup** [comment]
I will think about DNA support (at least, very light support) in the near future

**Comment by pstalcup** [comment]
After thinking about this a bit I believe that the way it should work is that you enable work shed swapping by setting a preference with the work sheds allowed (CSV) or "any" to allow it to pick from all of your work sheds

**Comment by libraryaddict** [comment]
More relevant than ever with the workshed change.
