### ISSUE TITLE
Canadv.ash not found?

### ISSUE THREAD

**Issue by solefate** [Loathing-Associates-Scripting-Society/garbage-collector#764]
When I tried to run Garbo for the first time after install, I got back 

too many matches for zlib.ash: D:\Program Files (x86)\KoL Mafia - Copy\scripts\zlib.ash; D:\Program Files (x86)\KoL Mafia - Copy\scripts\Quest Scripts\zlib.ash (canadv.ash, line 15, char 1 to char 18)
Script exception: Module "canadv.ash" not found.

Am I missing a dependancy?

**Comment by s-k-z** [comment]
Most likely, yes. Check if canadv.ash is installed. If not then you can install it via
```
svn checkout svn checkout https://svn.code.sf.net/p/therazekolmafia/canadv/code/
```
