### ISSUE TITLE
fix small but funny bug with copperhead club choice NC 

### ISSUE THREAD

**Issue by docrostov** [Loathing-Associates-Scripting-Society/garbage-collector#929]
![image](https://user-images.githubusercontent.com/8014761/170407899-616ceb09-8bcb-4d73-9650-ca3d82a69703.png)
the recent change that puts on a waiter outfit before fighting your evoke eldritch horror fight has a pretty funny interaction with copperhead. will put in a PR to fix this tomm probably.

**Comment by horrible-little-slime** [comment]
Noah fence but this does not need to be its own issue, this is part of the larger "unsupported choices" thing. It is a weird one, though, so fair to separate it. But also? unfair.
